package java_04_streams_76;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Java_08A_Difference_Between_map_And_flatMap_In_Java_Stream {

	public static void main(String[] args) {
		
		// making the array list object
		ArrayList<String> fruit = new ArrayList<>();
		fruit.add("Apple");
		fruit.add("mango");
		fruit.add("pineapple");
		fruit.add("kiwi");
		System.out.println("List of fruit-" + fruit);

		// lets use map() to convert list of fruit
		List list = fruit.stream().map(s -> s.length()).collect(Collectors.toList());
		System.out.println("List generated by map-" + list);
	}
}